# Generated by Django 4.1.7 on 2023-03-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_issue_status_alter_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(to='tracker.type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_issue', to='tracker.type', verbose_name='Тип'),
        ),
    ]
