# Generated by Django 4.1.7 on 2023-03-02 15:58

from django.db import migrations


def forward(apps, schema_editor):
    Issue = apps.get_model("tracker", "Issue")
    for issue in Issue.objects.all():
        issue.types.add(issue.type)


class Migration(migrations.Migration):
    dependencies = [
        ('tracker', '0003_issue_types_alter_issue_type'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
