# Generated by Django 4.1.7 on 2023-03-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_issue_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
    ]
