# Generated by Django 4.1.7 on 2023-03-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_project_created_at_project_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='tracker.project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
