# Generated by Django 4.1.7 on 2023-03-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_issue_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_deleted',
        ),
    ]
